spring.application.name=demo-app


# DataSource ??
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/db1?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA/Hibernate ??
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
# application.properties
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}



# application.properties
spring.jpa.open-in-view=false


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.web.resources.static-locations=file:${NUMBER_RECO_IMAGE_DIR:./img}/



server.servlet.session.cookie.secure=${SERVER_SESSION_COOKIE_SECURE:false}
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=${SERVER_SESSION_COOKIE_SAME_SITE:lax}
server.port=${PORT:8080}
